"""init

Revision ID: 5b287932865b
Revises: 1e35fda0b1c9
Create Date: 2026-01-18 07:05:39.068931
"""

from alembic import op
import sqlalchemy as sa



revision = '5b287932865b'
down_revision = '1e35fda0b1c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_channel', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('image_hash', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('image_format', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('orientation_corrected', sa.Boolean(), nullable=False),
    sa.Column('metadata_extracted', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_submissions_image_hash'), 'image_submissions', ['image_hash'], unique=True)
    op.create_index(op.f('ix_image_submissions_submitted_at'), 'image_submissions', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_image_submissions_user_id'), 'image_submissions', ['user_id'], unique=False)
    op.create_table('medgemma_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('modality', sa.String(), nullable=True),
    sa.Column('anatomical_region', sa.String(), nullable=True),
    sa.Column('key_findings', sa.Text(), nullable=True),
    sa.Column('clinical_impression', sa.Text(), nullable=True),
    sa.Column('findings_confidence', sa.Float(), nullable=True),
    sa.Column('image_quality_score', sa.Float(), nullable=True),
    sa.Column('quality_issues', sa.Text(), nullable=True),
    sa.Column('claimed_condition_analyzed', sa.Boolean(), nullable=False),
    sa.Column('claimed_vs_actual_match', sa.Float(), nullable=True),
    sa.Column('match_explanation', sa.Text(), nullable=True),
    sa.Column('contextual_inconsistencies', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('inference_time_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medgemma_analyses_analyzed_at'), 'medgemma_analyses', ['analyzed_at'], unique=False)
    op.create_table('submission_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('surrounding_text', sa.Text(), nullable=True),
    sa.Column('claimed_condition', sa.String(), nullable=True),
    sa.Column('claimed_origin', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_whatsapp_group', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_contexts')
    op.drop_index(op.f('ix_medgemma_analyses_analyzed_at'), table_name='medgemma_analyses')
    op.drop_table('medgemma_analyses')
    op.drop_index(op.f('ix_image_submissions_user_id'), table_name='image_submissions')
    op.drop_index(op.f('ix_image_submissions_submitted_at'), table_name='image_submissions')
    op.drop_index(op.f('ix_image_submissions_image_hash'), table_name='image_submissions')
    op.drop_table('image_submissions')
    # ### end Alembic commands ###
